### ISSUE TITLE
Failed to download article

### ISSUE THREAD

**Issue by TheKiteRunning** [mmagnus/Pocket-Plus-Calibre-Plugin#12]
Hi, I have installed the reciple and set as the readme file demonstrates, but unable to download any webpages, Thank you very much for your time! The following is the error message:

Fetch news from Pocket
Conversion options changed from defaults:
  output_profile: 'kindle_pw'
  verbose: 2
Resolved conversion options
calibre version: 3.13.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'dont_download_recipe': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x00000070D323CF28>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhiteOutput object at 0x00000070D32495F8>,
 'page_breaks_before': None,
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Using custom recipe
Synthesizing mastheadImage
Failed to download article: Is Google Making Us Stupid? from http://getpocket.com/a/read/208423309
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

Failed to download article: BuJoPro: Thoughts on Adapting Bullet Journal to a Hyper-Connected World from http://getpocket.com/a/read/1993533913
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

Failed to download article: The End of Facebook’s Ubiquity? from http://getpocket.com/a/read/1999812701
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

下载下列文章失败(The articles failed to download are:)：

Is Google Making Us Stupid? from My Pocket Articles for [06:47 下午]
http://getpocket.com/a/read/208423309
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

BuJoPro: Thoughts on Adapting Bullet Journal to a Hyper-Connected World from My Pocket Articles for [06:47 下午]
http://getpocket.com/a/read/1993533913
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

The End of Facebook’s Ubiquity? from My Pocket Articles for [06:47 下午]
http://getpocket.com/a/read/1999812701
Traceback (most recent call last):
  File "site-packages\calibre\utils\threadpool.py", line 100, in run
  File "site-packages\calibre\web\feeds\news.py", line 1152, in fetch_obfuscated_article
  File "<string>", line 155, in get_obfuscated_article
  File "<string>", line 140, in get_textview
  File "re.py", line 146, in search
TypeError: expected string or buffer

Parsing all content...
Parsing feed_0/index.html ...
Forcing feed_0/index.html into XHTML namespace
Parsing index.html ...
Forcing index.html into XHTML namespace
Reading TOC from NCX...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Found 2 items of level: p_2
Found 1 items of level: div_2
Found 3 items of level: div_1
Ignoring level p_2
div_2  left margin stats: Counter()
div_2  right margin stats: Counter()
div_1  left margin stats: Counter()
div_1  right margin stats: Counter()
Cleaning up manifest...
Trimming unused files from manifest...
Creating MOBI Output...
Serializing resources...
Using mastheadImage supplied in manifest...
Creating MOBI 6 output
Applying case-transforming CSS...
Parsing manglecase.css ...
Rasterizing SVG images...
Converting XHTML to Mobipocket markup...
Serializing markup content...
  Compressing markup content...
No TOC, MOBI index not generated
MOBI output written to C:\Users\123\AppData\Local\Temp\calibre_pe9k1l\tz6ark_recipe_out.mobi

Thank you for your help!

**Comment by mmagnus** [comment]
#9  the same issue, now solved!
