### ISSUE TITLE
Can't download more that 43 Article

### ISSUE THREAD

**Issue by Monirzadeh** [mmagnus/Pocket-Plus-Calibre-Plugin#13]
hi
i use this plugin and it's work fine, if you set variable  `oldest_article` and `max_articles_per_feed` 43 or less than that
if you try to get article more than 43 item, plugin can't fetch article and give you this error 
i have more than 500 item in my pocket
```
Fetch news from Pocket [mylist] 
Conversion options changed from defaults:
  output_profile: u'kindle_pw3'
  verbose: 2
Resolved conversion options
calibre version: 4.8.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': u'original',
 'chapter': None,
 'chapter_mark': u'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'dont_download_recipe': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7fe60c489ed0>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'mobi_file_type': u'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7fe60c490710>,
 'page_breaks_before': None,
 'personal_doc': u'[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': u'',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': u'',
 'sr1_search': u'',
 'sr2_replace': u'',
 'sr2_search': u'',
 'sr3_replace': u'',
 'sr3_search': u'',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: custom:1001
Using user agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Traceback (most recent call last):
  File "site.py", line 77, in main
  File "site-packages/calibre/utils/ipc/worker.py", line 209, in main
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 36, in gui_convert_recipe
  File "site-packages/calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "site-packages/calibre/ebooks/conversion/plumber.py", line 1110, in run
  File "site-packages/calibre/customize/conversion.py", line 246, in __call__
  File "site-packages/calibre/ebooks/conversion/plugins/recipe_input.py", line 139, in convert
  File "site-packages/calibre/web/feeds/news.py", line 1022, in download
  File "site-packages/calibre/web/feeds/news.py", line 1190, in build_index
  File "<string>", line 244, in parse_index
  File "<string>", line 244, in <lambda>
KeyError: u'sort_id'
```

**Comment by mmagnus** [comment]
OK, thanks guys, I will look into that, and #14.

**Comment by pjft** [comment]
In case it helps, I was having this error and when I changed the variable "to_pull" from "all" to 'unread' it started working and I could download my 300+ articles in one fell swoop.

**Comment by Monirzadeh** [comment]
> In case it helps, I was having this error and when I changed the variable "to_pull" from "all" to 'unread' it started working and I could download my 300+ articles in one fell swoop.
> 
> Might be completely unrelated, but worth a try.

it is work and start download near 999 article but for now it work on epub generation step.
 it is take time  (12 hours unitl now) and it is not finish yet.

**Comment by mmagnus** [comment]
https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/releases/tag/v2.3.2 

- attempt to fix sort_id problem
- improve docs
- cleaner code
- move OLDEST_ARTICLE to the top
