### ISSUE TITLE
Issue to fetch news

### ISSUE THREAD

**Issue by williamjamir** [mmagnus/Pocket-Plus-Calibre-Plugin#54]
I followed all the steps from the installation instructions, with everything on default (I didn't change any settings).
I linked my Pocket account, and no issue was shown:

Calibre version 6.11
Ubuntu 23.04

![image](https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin/assets/5083518/10b43ce6-bf4d-40ec-87a4-8db1138fb772)

But when I click to fetch the news I see the following error:
```python
Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_recipe
    gui_convert('from-gui.recipe', output, recommendations, notification=notification,
  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
    plumber.run()
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
    self.oeb = self.input_plugin(stream, self.opts,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/conversion.py", line 242, in __call__
    ret = self.convert(stream, options, file_ext,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/recipe_input.py", line 137, in convert
    ro = recipe(opts, log, self.report_progress)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/web/feeds/news.py", line 932, in __init__
    self.browser = self.get_browser()
                   ^^^^^^^^^^^^^^^^^^
  File "<string>", line 423, in get_browser
  File "<string>", line 418, in ensure_authorization
  File "<string>", line 263, in authorize
  File "<string>", line 252, in authorize
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 500: Internal Server Error
``` 

<details>
  <summary>Full stacktrace with all settings</summary>
  
  ```python
`calibre, version 6.11.0 (linux, embedded-python: False)
Erro ao converter: Falha: Obter notícias de Pocket

Obter notícias de Pocket
Conversion options changed from defaults:
  verbose: 2
Resolved conversion options
calibre version: 6.11.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': None,
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': None,
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_download_recipe': False,
 'dont_split_on_page_breaks': True,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'epub_flatten': False,
 'epub_inline_toc': False,
 'epub_toc_at_end': False,
 'epub_version': '2',
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': None,
 'fix_indents': True,
 'flow_size': 260,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f512d679150>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0,
 'linearize_tables': False,
 'lrf': False,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'markup_chapter_headings': True,
 'max_toc_links': 50,
 'minimum_line_height': 120.0,
 'no_chapters_in_toc': False,
 'no_default_epub_cover': False,
 'no_inline_navbars': False,
 'no_svg_cover': False,
 'output_profile': <calibre.customize.profiles.OutputProfile object at 0x7f512d684410>,
 'page_breaks_before': None,
 'prefer_metadata_cover': False,
 'preserve_cover_aspect_ratio': False,
 'pretty_print': True,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': None,
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': None,
 'series': None,
 'series_index': None,
 'smarten_punctuation': False,
 'sr1_replace': '',
 'sr1_search': '',
 'sr2_replace': '',
 'sr2_search': '',
 'sr3_replace': '',
 'sr3_search': '',
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'test': False,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': None,
 'transform_html_rules': None,
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2}
InputFormatPlugin: Recipe Input running
Downloading recipe urn: custom:1000
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Traceback (most recent call last):
  File "/usr/bin/calibre-parallel", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/calibre/calibre/utils/ipc/worker.py", line 215, in main
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 31, in gui_convert_recipe
    gui_convert('from-gui.recipe', output, recommendations, notification=notification,
  File "/usr/lib/calibre/calibre/gui2/convert/gui_conversion.py", line 25, in gui_convert
    plumber.run()
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 1108, in run
    self.oeb = self.input_plugin(stream, self.opts,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/customize/conversion.py", line 242, in __call__
    ret = self.convert(stream, options, file_ext,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/plugins/recipe_input.py", line 137, in convert
    ro = recipe(opts, log, self.report_progress)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/web/feeds/news.py", line 932, in __init__
    self.browser = self.get_browser()
                   ^^^^^^^^^^^^^^^^^^
  File "<string>", line 423, in get_browser
  File "<string>", line 418, in ensure_authorization
  File "<string>", line 263, in authorize
  File "<string>", line 252, in authorize
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.get_seek_wrapper_class.<locals>.httperror_seek_wrapper: HTTP Error 500: Internal Server Error
  ```
</details>

**Comment by alvaroreig** [comment]
Can you check out if this file exist?

`/home/$USER/.config/calibre/custom_recipes/Pocket.json `

**Comment by williamjamir** [comment]
Yeap, indeed it exists:

``` 
❯ cat /home/$USER/.config/calibre/custom_recipes/Pocket.json 
{"state": 2, "token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxx", "user": null}
``` 

I've tried to revoke the access and make the logging again (deleting this file as well), but I still get the same error (with the same file content, but only changing the token).

I followed the same steps from the README, clicked on the link, made the authentication, clicked to approve, and the page was redirected to the main page of Calibre.

**Comment by alvaroreig** [comment]
Hi there,

I've tried to replicate your issue.

I was using an out of date version of calibre, so I updated to the last one (6.23) and the last version of the recipe. I am using Linux Mint 21.1 which uses Ubuntu 22.04 under the hood.

With that setup, it works:

```
$ ebook-convert Pocket.recipe test.epub
Conversion options changed from defaults:
  test: None
1% Converting input to HTML...
InputFormatPlugin: Recipe Input running
Using custom recipe
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
1% Fetching feeds...
1% Got feeds from index page
1% Trying to download cover...
1% Generating masthead...
34% Masthead image downloaded
1% Starting download [10 threads]...
2% Article downloaded: "XXXXX"
3% Article downloaded: XXXXXXXX
qt.gui.icc: fromIccProfile: failed minimal tag size sanity
```
Can you update calibre and post the output of:

`ebook-convert Pocket.recipe test.epub -d -v`

To check if it outpus any new information?

I though the key could be that Ubuntu 23.04 no longer supports Python 2.X, and the recipe is pointing to 2.7:

```
#!/usr/bin/env python
# vim:ft=python tabstop=8 expandtab shiftwidth=4 softtabstop=4
from __future__ import print_function
__version__ = '2.7.4'

```
But I pointed the recipe to 3.10.6 (which I have installed in my system) and it worked anyway.

@mmagnus what do you think?

**Comment by williamjamir** [comment]
I think updating Calibre solved the issue :)
I cleaned everything (revoked access) and executed the command:
``` 
❯ ebook-convert Pocket.recipe test.epub -d -v
Conversion options changed from defaults:
  debug_pipeline: '-v'
  test: None
1% Converting input to HTML...
InputFormatPlugin: Recipe Input running
Using custom recipe
Using user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Failed to download Pocket

                                Calibre must be granted access to your Pocket account. Please click
                                <a href="https://getpocket.com/auth/authorize?request_token=<_TOKEN>&redirect_uri=https://calibre-ebook.com/">here</a>
                                to authenticate via a browser, and then re-fetch the news.
``` 

So I copied the URL and made the authentication again.

And now the file was updated and the sync was completed:
```
/opt/Pocket-Plus-Calibre-Plugin-master 
❯ cat /home/$USER/.config/calibre/custom_recipes/Pocket.json
{"state": 3, "token": "<_TOKEN>", "user": "<MY_USER>"}
``` 

Executing the command

``` 
ebook-convert Pocket.recipe test.epub -d -v
Conversion options changed from defaults:
  debug_pipeline: '-v'
  test: None
1% Converting input to HTML...
InputFormatPlugin: Recipe Input running
Using custom recipe
Using user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
1% Fetching feeds...
1% Got feeds from index page
1% Trying to download cover...
1% Generating masthead...
34% Masthead image downloaded
1% Starting download [10 threads]...
34% Article downloaded:
....

```


Thanks for the help!
