### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6

### ISSUE THREAD

**Issue by panweihwa** [mmagnus/Pocket-Plus-Calibre-Plugin#7]
Bug report

I have tried Calibre pocket+ recipe for two days in different computers with different version of calibre (v1.48 for chinese XP to most updated v2.85 on chinese win7). However, similar bug happens and the calibre process terminates while fetching data all the time. 

I post the error messages below. I guess the main reasons are related to the Chinese text encoded format.

The original pocket recipe which the pocket+ modified from is working ok on my machine. Yet, there is a warning message on the log file: 
----------------------
WARNING: Encoding detection confidence for utf-8 is 99%
Parsed
----------------------
Hope anyone can help to solve the problem. 

Thank you for your dedication.

Hereafter is the last trackback log file in details.
----------------------------------------
Downloaded article: 倭寇，一個王朝的謊言 from https://getpocket.com/a/read/1651214851
Python function terminated unexpectedly
'utf8' codec can't decode byte 0xd6 in position 9: invalid continuation byte (Error Code: 1)
Traceback (most recent call last):
File "site.py", line 132, in main
File "site.py", line 109, in run_entry_point
File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
File "site-packages\calibre\customize\conversion.py", line 245, in __call__
File "site-packages\calibre\ebooks\conversion\plugins\recipe_ input.py", line 119, in convert
File "site-packages\calibre\web\feeds\news.py", line 1019, in download
File "site-packages\calibre\web\feeds\news.py", line 1275, in build_index
File "site-packages\calibre\web\feeds\news.py", line 1419, in create_opf
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 9: invalid continuation byte

**Comment by panweihwa** [comment]
The original pocket recipe which the pocket+ modified from is working ok on my machine. Yet, there is a warning message on the log file:
WARNING: Encoding detection confidence for utf-8 is 99%
Parsed

**Comment by mmagnus** [comment]
@panweihwa  can you upload here a link to the article that caused the crash, please

**Comment by panweihwa** [comment]
The last article link is https://getpocket.com/a/read/1651214851, entitled as "倭寇，一個王朝的謊言"
However, I suspect that it is not the link causing collapse, according to the last traceback, the crash caused by creating opf file. 

Please see previous original post for details.

**Comment by mmagnus** [comment]
@panweihwa but i need a link to re-generate the problem to see what's wrong. Now I have it :-)

**Comment by mmagnus** [comment]
![screen shot 2017-05-22 at 12 20 27 pm](https://cloud.githubusercontent.com/assets/118740/26303774/140987f4-3ee9-11e7-9a5b-9bcd1c39ee43.png)

it seems to work in my case. Can you check if you are using the latest version of programs, Calibre and the plugin?

**Comment by panweihwa** [comment]
I am trying to run the most updated Calibre 1.85.1 on the Chinese win10 OS in my Office. The problem still happened.
It is terminated by the same bug. Is it because I am running on Chinese OS?

-----------------------------------------------
Downloaded article: 國家財政困難 李來希：為何有前瞻計畫？ from https://getpocket.com/a/read/1737876159
Fetching file:c:\tmp\_user_\tmpbvspoi
Fetched c:\tmp\_user_\tmpbvspoi in 0.0 seconds
Parsed file:c:\tmp\_user_\tmpbvspoi in 0.0 seconds
Processing images...
Fetching http://www.daliulian.net/imgs/image/59/5951234.jpg
Fetched http://www.daliulian.net/imgs/image/59/5951234.jpg in 0.458000 seconds
Fetching http://www.daliulian.net/imgs/image/59/5951235.jpg
Fetched http://www.daliulian.net/imgs/image/59/5951235.jpg in 0.379000 seconds
Fetching http://www.circle01.com/imgs/image/59/5951233.jpg
Fetched http://www.circle01.com/imgs/image/59/5951233.jpg in 0.413000 seconds
Recursion limit reached. Skipping links in file:c:\tmp\_user_\tmpbvspoi
file:c:\tmp\_user_\tmpbvspoi saved to C:\Tmp\_User_\calibre_tgesxw\xymlog_plumber\feed_0\article_29\index.xhtml
Downloaded article: 原來這就是高血壓的真相，每天吃降壓藥的人都竟然不知道！快轉給身邊有高血壓的人知道吧！ from https://getpocket.com/a/read/1711834762
Python function terminated unexpectedly
  'utf8' codec can't decode byte 0xb6 in position 9: invalid start byte (Error Code: 1)
Traceback (most recent call last):
  File "site.py", line 132, in main
  File "site.py", line 109, in run_entry_point
  File "site-packages\calibre\utils\ipc\worker.py", line 195, in main
  File "site-packages\calibre\gui2\convert\gui_conversion.py", line 26, in gui_convert
  File "site-packages\calibre\ebooks\conversion\plumber.py", line 1088, in run
  File "site-packages\calibre\customize\conversion.py", line 245, in __call__
  File "site-packages\calibre\ebooks\conversion\plugins\recipe_input.py", line 119, in convert
  File "site-packages\calibre\web\feeds\news.py", line 1019, in download
  File "site-packages\calibre\web\feeds\news.py", line 1275, in build_index
  File "site-packages\calibre\web\feeds\news.py", line 1419, in create_opf
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 9: invalid start byte

**Comment by mmagnus** [comment]
you can post it to Calibre issue tracker maybe.. hmm.. It will be hard for me to "fix it" since I have no problem with this. I have articles in Polish (with żąó) and it works so I don't know why it does work with Chinese.

**Comment by panweihwa** [comment]
I changed the maximum downloaded article to only 3, still crashed. It seems to me that the error occurred while creating OPF file always, not related to links.

File "site-packages\calibre\web\feeds\news.py", line 1403, in create_opf
UnicodeDecodeError: 'utf8' codec can't decode byte 0xac in position 9: invalid start byte

**Comment by mmagnus** [comment]
It might be a problem of Calibre itself. Report it to them and maybe they can help.
